name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: "npm i"
          command: deploy
